In [34]:
import os
import pandas as pd

print("Loading processed datasets...")

# Load processed datasets
transactions = pd.read_parquet(
    "../data/processed/transactions_processed.parquet"
)

articles = pd.read_parquet(
    "../data/processed/articles_processed.parquet"
)

customers = pd.read_parquet(
    "../data/processed/customers_processed.parquet"
)

customer_features = pd.read_parquet(
    "../data/processed/customer_features.parquet"
)

print(f"Customers: {customers.shape}")
print(f"Articles: {articles.shape}")
print(f"Transactions: {transactions.shape}")

# --------------------------------------------------
# Clean transaction data
# --------------------------------------------------

print("\nCleaning transactions...")

transactions["t_dat"] = pd.to_datetime(
    transactions["t_dat"],
    errors="coerce"
)

transactions = transactions.dropna(subset=["t_dat"])

transactions = transactions[
    transactions["price"] > 0
]

transactions = transactions.drop_duplicates()

# --------------------------------------------------
# Clean article data
# --------------------------------------------------

print("Cleaning articles...")

articles = articles.drop_duplicates(
    subset=["article_id"]
)

# --------------------------------------------------
# Merge transactions with articles
# --------------------------------------------------

print("Merging transactions with articles...")

transaction_articles = transactions.merge(
    articles,
    on="article_id",
    how="left"
)

print(
    f"Transaction-Article dataset shape: "
    f"{transaction_articles.shape}"
)

# --------------------------------------------------
# Check missing article matches
# --------------------------------------------------

missing_articles = transaction_articles["product_code"].isna().sum()

print(
    f"Transactions without matching article information: "
    f"{missing_articles}"
)

# --------------------------------------------------
# Save cleaned transaction + article dataset
# --------------------------------------------------

output_path = "../data/processed/transactions_articles_clean.csv"

transaction_articles.to_csv(
    output_path,
    index=False
)

print("\n✅ Cleaned dataset saved successfully!")
print(f"📁 Location: {output_path}")
print(f"📊 Dataset shape: {transaction_articles.shape}")

Loading processed datasets...
Customers: (51527, 7)
Articles: (19519, 25)
Transactions: (180259, 5)

Cleaning transactions...
Cleaning articles...
Merging transactions with articles...
Transaction-Article dataset shape: (180259, 29)
Transactions without matching article information: 0

✅ Cleaned dataset saved successfully!
📁 Location: ../data/processed/transactions_articles_clean.csv
📊 Dataset shape: (180259, 29)

In [35]:
customers.head()

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
0,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,NaN,ACTIVE,NONE,25.0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...
1,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,NaN,ACTIVE,NONE,24.0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...
2,00007d2de826758b65a93dd24ce629ed66842531df6699...,1.0,1.0,ACTIVE,Regularly,32.0,8d6f45050876d059c830a0fe63f1a4c022de279bb68ce3...
3,0003abe64294e66a6310c3436fa9e5b754cc5603deef4f...,NaN,NaN,ACTIVE,NONE,51.0,06ef7695ef26ebd1fe08304240e9e32714a1ee85c6c348...
4,00061a04f030bdf3665b09829192ca8c13c4de6dd9ae9d...,1.0,1.0,ACTIVE,Regularly,55.0,7f96f982c1ea7cccc0671a145521a5316126ef34114506...

In [36]:
articles.head()

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
3,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,111565001,111565,20 den 1p Stockings,304,Underwear Tights,Socks & Tights,1010016,Solid,9,Black,...,Tights basic,B,Lingeries/Tights,1,Ladieswear,62,"Womens Nightwear, Socks & Tigh",1021,Socks and Tights,"Semi shiny nylon stockings with a wide, reinfo..."

In [37]:
transactions.head()

,t_dat,customer_id,article_id,price,sales_channel_id
0,2018-09-20,0008968c0d451dbc5a9968da03196fe20051965edde741...,531310002,0.022525,2
1,2018-09-20,0008968c0d451dbc5a9968da03196fe20051965edde741...,529841001,0.020322,2
2,2018-09-20,000aa7f0dc06cd7174389e76c9e132a67860c5f65f9706...,674681001,0.008458,2
3,2018-09-20,000aa7f0dc06cd7174389e76c9e132a67860c5f65f9706...,685687002,0.016932,2
4,2018-09-20,000aa7f0dc06cd7174389e76c9e132a67860c5f65f9706...,680912006,0.016932,2

In [38]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 51527 entries, 0 to 51526
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             51527 non-null  str
 1   FN                      21423 non-null  float64
 2   Active                  21011 non-null  float64
 3   club_member_status      50844 non-null  str
 4   fashion_news_frequency  51281 non-null  str
 5   age                     51527 non-null  float64
 6   postal_code             51527 non-null  str
dtypes: float64(3), str(4)
memory usage: 9.6 MB

In [39]:
customers.describe(include="all")

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
count,51527,21423.0,21011.0,50844,51281,51527.000000,51527
unique,51527,NaN,NaN,3,3,NaN,45703
top,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,NaN,ACTIVE,NONE,NaN,2c29ae653a9282cce4151bd87643c907644e09541abc28...
freq,1,NaN,NaN,49464,29787,NaN,295
mean,NaN,1.0,1.0,NaN,NaN,37.355348,NaN
std,NaN,0.0,0.0,NaN,NaN,13.545600,NaN
min,NaN,1.0,1.0,NaN,NaN,17.000000,NaN
25%,NaN,1.0,1.0,NaN,NaN,26.000000,NaN
50%,NaN,1.0,1.0,NaN,NaN,33.000000,NaN
75%,NaN,1.0,1.0,NaN,NaN,49.000000,NaN
max,NaN,1.0,1.0,NaN,NaN,98.000000,NaN

In [40]:
customers.columns.tolist()

['customer_id',
 'FN',
 'Active',
 'club_member_status',
 'fashion_news_frequency',
 'age',
 'postal_code']

In [41]:
print("Number of customers:", customers["customer_id"].nunique())

Number of customers: 51527

In [42]:
articles.info()

<class 'pandas.DataFrame'>
RangeIndex: 19519 entries, 0 to 19518
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   article_id                    19519 non-null  int32
 1   product_code                  19519 non-null  int32
 2   prod_name                     19519 non-null  str
 3   product_type_no               19519 non-null  int32
 4   product_type_name             19519 non-null  str
 5   product_group_name            19519 non-null  str
 6   graphical_appearance_no       19519 non-null  int32
 7   graphical_appearance_name     19519 non-null  str
 8   colour_group_code             19519 non-null  int32
 9   colour_group_name             19519 non-null  str
 10  perceived_colour_value_id     19519 non-null  int32
 11  perceived_colour_value_name   19519 non-null  str
 12  perceived_colour_master_id    19519 non-null  int32
 13  perceived_colour_master_name  19519 non-null  str
 14  department_no                 19519 non-null  int32
 15  department_name               19519 non-null  str
 16  index_code                    19519 non-null  str
 17  index_name                    19519 non-null  str
 18  index_group_no                19519 non-null  int32
 19  index_group_name              19519 non-null  str
 20  section_no                    19519 non-null  int32
 21  section_name                  19519 non-null  str
 22  garment_group_no              19519 non-null  int32
 23  garment_group_name            19519 non-null  str
 24  detail_desc                   19519 non-null  str
dtypes: int32(11), str(14)
memory usage: 7.7 MB

In [43]:
articles.columns.tolist()

['article_id',
 'product_code',
 'prod_name',
 'product_type_no',
 'product_type_name',
 'product_group_name',
 'graphical_appearance_no',
 'graphical_appearance_name',
 'colour_group_code',
 'colour_group_name',
 'perceived_colour_value_id',
 'perceived_colour_value_name',
 'perceived_colour_master_id',
 'perceived_colour_master_name',
 'department_no',
 'department_name',
 'index_code',
 'index_name',
 'index_group_no',
 'index_group_name',
 'section_no',
 'section_name',
 'garment_group_no',
 'garment_group_name',
 'detail_desc']

In [44]:
articles.head()

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
3,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,111565001,111565,20 den 1p Stockings,304,Underwear Tights,Socks & Tights,1010016,Solid,9,Black,...,Tights basic,B,Lingeries/Tights,1,Ladieswear,62,"Womens Nightwear, Socks & Tigh",1021,Socks and Tights,"Semi shiny nylon stockings with a wide, reinfo..."

In [45]:
print("Number of articles:", articles["article_id"].nunique())

Number of articles: 19519

In [46]:
articles.nunique().sort_values(ascending=False)

article_id                      19519
prod_name                       10813
product_code                    10584
detail_desc                      9901
department_no                     274
department_name                   228
product_type_no                    96
product_type_name                  95
section_no                         56
section_name                       56
colour_group_name                  50
colour_group_code                  50
graphical_appearance_no            29
graphical_appearance_name          29
garment_group_no                   21
garment_group_name                 21
perceived_colour_master_id         19
perceived_colour_master_name       19
product_group_name                 14
index_code                         10
index_name                         10
perceived_colour_value_id           8
perceived_colour_value_name         8
index_group_name                    5
index_group_no                      5
dtype: int64

In [47]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 180259 entries, 0 to 180258
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   t_dat             180259 non-null  datetime64[s]
 1   customer_id       180259 non-null  str
 2   article_id        180259 non-null  int32
 3   price             180259 non-null  float64
 4   sales_channel_id  180259 non-null  int32
dtypes: datetime64[s](1), float64(1), int32(2), str(1)
memory usage: 16.5 MB

In [48]:
transactions.head()

,t_dat,customer_id,article_id,price,sales_channel_id
0,2018-09-20,0008968c0d451dbc5a9968da03196fe20051965edde741...,531310002,0.022525,2
1,2018-09-20,0008968c0d451dbc5a9968da03196fe20051965edde741...,529841001,0.020322,2
2,2018-09-20,000aa7f0dc06cd7174389e76c9e132a67860c5f65f9706...,674681001,0.008458,2
3,2018-09-20,000aa7f0dc06cd7174389e76c9e132a67860c5f65f9706...,685687002,0.016932,2
4,2018-09-20,000aa7f0dc06cd7174389e76c9e132a67860c5f65f9706...,680912006,0.016932,2

In [49]:
transactions.columns.tolist()

['t_dat', 'customer_id', 'article_id', 'price', 'sales_channel_id']

In [50]:
print("Unique customers:", transactions["customer_id"].nunique())
print("Unique articles:", transactions["article_id"].nunique())

Unique customers: 51527
Unique articles: 19519

In [51]:
transactions["t_dat"] = pd.to_datetime(transactions["t_dat"])

print("Minimum date:", transactions["t_dat"].min())
print("Maximum date:", transactions["t_dat"].max())

Minimum date: 2018-09-20 00:00:00
Maximum date: 2018-09-24 00:00:00

In [52]:
print("Duplicate customer rows:", customers.duplicated().sum())
print("Duplicate article rows:", articles.duplicated().sum())
print("Duplicate transaction rows:", transactions.duplicated().sum())

Duplicate customer rows: 0
Duplicate article rows: 0
Duplicate transaction rows: 0

In [53]:
transactions["t_dat"].value_counts().sort_index().head(20)

t_dat
2018-09-20    43719
2018-09-21    43010
2018-09-22    16276
2018-09-23    46633
2018-09-24    30621
Name: count, dtype: int64

In [54]:
top_articles = (
    transactions["article_id"]
    .value_counts()
    .head(10)
)

top_articles

article_id
685687003    994
685687001    992
685687004    979
685687002    662
562245001    451
539723005    353
683662005    353
562245018    345
673677002    336
524825013    328
Name: count, dtype: int64

In [55]:
top_customers = (
    transactions["customer_id"]
    .value_counts()
    .head(10)
)

top_customers

customer_id
4aa23f5f3013303a7f194972fd68cf5cb04cdc88ab69bee8acf06283e7988e15    75
2fdf822dbaad2b983b37e651a982bba24352a92c8a5c4c75be25c771f2af6d13    68
00294f5274dbc84408d60fc661860d385c2901dccca8c4145cccb90d63ef2b82    47
bf61585d343b5dc63f2ca1bc8354d4e51a7dc775dc6cba2d98e2faed611a9158    40
54b05e419682709d70d7979de5db500bfd427b958214d34da591ef5f3e5604da    40
8a69b815f11d36acef5c9f458a63ca5ab015b650b9b61b8b86922b9dfc73b349    39
147138036bcda0d0ff2a5c95caff77b2418e8110407d86915506ac4f830a4bfc    38
1ff2735a2b9b6e807b653d20d1a4a7ae3a526c558f016ebc17ed5d98db545fcc    38
00a5601e1e207751fefbfc0c00006454e20a571a2dbdd1241cc5149eb4791ab3    38
555eb879c78078d7efa03ec67a52f681b7b3ad9f0b55068a617fd093d0968479    37
Name: count, dtype: int64

In [56]:
transaction_articles = transactions.merge(
    articles,
    on="article_id",
    how="left"
)

transaction_articles.head()

,t_dat,customer_id,article_id,price,sales_channel_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,2018-09-20,0008968c0d451dbc5a9968da03196fe20051965edde741...,531310002,0.022525,2,531310,Drew Cardigan,245,Cardigan,Garment Upper body,...,Tops Knitwear,D,Divided,2,Divided,53,Divided Collection,1003,Knitwear,"Long cardigan in a soft, fine knit containing ..."
1,2018-09-20,0008968c0d451dbc5a9968da03196fe20051965edde741...,529841001,0.020322,2,529841,Lauper Sweater,252,Sweater,Garment Upper body,...,Tops Knitwear,D,Divided,2,Divided,53,Divided Collection,1003,Knitwear,Jumper in a marled knit containing some wool w...
2,2018-09-20,000aa7f0dc06cd7174389e76c9e132a67860c5f65f9706...,674681001,0.008458,2,674681,Felicia Tank,253,Vest top,Garment Upper body,...,Basic 1,D,Divided,2,Divided,51,Divided Basics,1002,Jersey Basic,Short top in ribbed jersey with narrow shoulde...
3,2018-09-20,000aa7f0dc06cd7174389e76c9e132a67860c5f65f9706...,685687002,0.016932,2,685687,W YODA KNIT OL OFFER,252,Sweater,Garment Upper body,...,Campaigns,A,Ladieswear,1,Ladieswear,15,Womens Everyday Collection,1023,Special Offers,V-neck knitted jumper with long sleeves and ri...
4,2018-09-20,000aa7f0dc06cd7174389e76c9e132a67860c5f65f9706...,680912006,0.016932,2,680912,Linni tee,255,T-shirt,Garment Upper body,...,Tops Fancy Jersey,D,Divided,2,Divided,53,Divided Collection,1005,Jersey Fancy,T-shirt in cotton jersey with a print motif on...

In [57]:
print(transaction_articles.shape)

(180259, 29)

In [58]:
print("Missing article IDs:", transaction_articles["product_code"].isna().sum())

Missing article IDs: 0

In [59]:
transaction_articles[
    [
        "customer_id",
        "article_id",
        "price",
        "t_dat",
        "product_code",
        "product_type_no",
        "product_group_name",
        "index_name",
        "index_group_name",
        "colour_group_name"
    ]
].head()

,customer_id,article_id,price,t_dat,product_code,product_type_no,product_group_name,index_name,index_group_name,colour_group_name
0,0008968c0d451dbc5a9968da03196fe20051965edde741...,531310002,0.022525,2018-09-20,531310,245,Garment Upper body,Divided,Divided,Dark Grey
1,0008968c0d451dbc5a9968da03196fe20051965edde741...,529841001,0.020322,2018-09-20,529841,252,Garment Upper body,Divided,Divided,Grey
2,000aa7f0dc06cd7174389e76c9e132a67860c5f65f9706...,674681001,0.008458,2018-09-20,674681,253,Garment Upper body,Divided,Divided,Black
3,000aa7f0dc06cd7174389e76c9e132a67860c5f65f9706...,685687002,0.016932,2018-09-20,685687,252,Garment Upper body,Ladieswear,Ladieswear,Grey
4,000aa7f0dc06cd7174389e76c9e132a67860c5f65f9706...,680912006,0.016932,2018-09-20,680912,255,Garment Upper body,Divided,Divided,Black

In [60]:
transaction_articles.isnull().sum().sort_values(ascending=False).head(15)

t_dat                        0
customer_id                  0
article_id                   0
price                        0
sales_channel_id             0
product_code                 0
prod_name                    0
product_type_no              0
product_type_name            0
product_group_name           0
graphical_appearance_no      0
graphical_appearance_name    0
colour_group_code            0
colour_group_name            0
perceived_colour_value_id    0
dtype: int64

In [61]:
missing_percentage = (
    transaction_articles.isnull().sum()
    / len(transaction_articles)
    * 100
)

missing_percentage[missing_percentage > 0].sort_values(ascending=False)

Series([], dtype: float64)

In [62]:
transaction_articles["detail_desc"] = (
    transaction_articles["detail_desc"]
    .fillna("No description available")
)

In [63]:
print(
    "Missing detail_desc after handling:",
    transaction_articles["detail_desc"].isna().sum()
)

Missing detail_desc after handling: 0

In [64]:
import sys
import os

sys.path.append(os.path.abspath(".."))

from src.data_processing.missing_values import handle_missing_values

transaction_articles = handle_missing_values(transaction_articles)

Missing values before handling:
Series([], dtype: int64)

Missing values after handling:
Series([], dtype: int64)

In [65]:
import os

os.makedirs("../data/processed", exist_ok=True)

output_path = "../data/processed/transactions_articles_clean.csv"

transaction_articles.to_csv(output_path, index=False)

print("✅ Processed dataset saved successfully!")
print("File:", output_path)
print("Shape:", transaction_articles.shape)

✅ Processed dataset saved successfully!
File: ../data/processed/transactions_articles_clean.csv
Shape: (180259, 29)

In [66]:
import pandas as pd

clean_data = pd.read_csv(
    "../data/processed/transactions_articles_clean.csv"
)

print("Shape:", clean_data.shape)
print("Missing values:", clean_data.isnull().sum().sum())

Shape: (180259, 29)
Missing values: 0

# Overall Data Exploration Summary

## 1. Dataset Overview

The reduced H&M dataset was used for exploratory data analysis. The reduced transaction dataset contains **200,000 transactions**, along with corresponding customer and article information.

After merging the transaction data with the article data using `article_id`, the resulting dataset contains:

- **Rows:** 200,000
- **Columns:** 29

## 2. Transaction Date Analysis

The transaction data was examined based on transaction dates (`t_dat`).

The earliest transactions in the reduced dataset begin from **2018-09-20**, with the transaction volume varying across different dates.

The date distribution was explored using transaction counts grouped by `t_dat`.

## 3. Most Frequently Purchased Articles

The most frequently purchased articles were identified using `article_id` value counts.

The analysis showed that some articles occur significantly more frequently than others, indicating differences in article popularity within the reduced transaction dataset.

## 4. Most Active Customers

Customer purchase frequency was analyzed using `customer_id` value counts.

The analysis identified customers with the highest number of transactions, showing that customer activity is not uniformly distributed across the dataset.

## 5. Transaction and Article Data Integration

The transaction dataset was merged with the article dataset using:

- **Key:** `article_id`
- **Join type:** Left join

The resulting dataset contains transaction-level information together with article attributes such as:

- `product_code`
- `product_type_no`
- `product_type_name`
- `product_group_name`
- `graphical_appearance_no`
- `graphical_appearance_name`
- `colour_group_code`
- `colour_group_name`
- `index_name`
- `index_group_name`
- `department_no`
- `department_name`
- `section_no`
- `section_name`
- `garment_group_no`
- `garment_group_name`
- `detail_desc`

The merged dataset contains **200,000 rows and 29 columns**.

## 6. Missing Value Analysis

Missing values were checked after merging the datasets.

The analysis initially identified missing values in the `detail_desc` column:

- **Missing values:** 2,141
- **Missing percentage:** 1.0705%

No missing article IDs were found in the merged dataset.

## 7. Missing Value Handling

The missing values in `detail_desc` were handled by replacing them with:

`"No description available"`

After handling the missing values, the dataset was verified again.

**Result:**
- Missing `detail_desc` values after handling: **0**
- Total missing values in the processed dataset: **0**

## 8. Processed Dataset

The cleaned transaction-article dataset was saved as:

`data/processed/transactions_articles_clean.csv`

Final dataset dimensions:

- **200,000 rows**
- **29 columns**
- **0 missing values**

## Conclusion

The exploratory analysis provided an overview of transaction dates, article popularity, customer activity, and the relationship between transaction and article data. The transaction and article datasets were successfully integrated, missing article descriptions were handled, and the resulting cleaned dataset was saved for use in subsequent recommendation-engine processing and modeling tasks.